[package]
name = "expert_system"
version = "0.1.0"
authors = ["gpoblon <gpoblon@student.42.fr>", "jmichaud <jmichaud@student.42.fr>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "expert_system"
path = "src/bin/main.rs"

[dependencies]
